control:
  uri: "http://192.0.2.3:8080"
  bind-addr: "192.0.2.3:8080"

pfcp: "203.0.113.1"

slices:
  nextmn-lite:
    pool: "10.0.0.0/24"
    upfs:
      - node-id: "203.0.113.2" # srgw1
        interfaces:
          - type: "N3"
            addr: "198.51.100.11"
      - node-id: "203.0.113.3" # srgw2
        interfaces:
          - type: "N3"
            addr: "198.51.100.12"

areas: # RAN areas
  area1:
    gnbs: # list of gnbs in the area
      - "http://192.0.2.2:8080" # gnb1
      - "http://192.0.2.4.8080" # gnb2
    paths: # define one path per slice
      nextmn-lite:
        - "203.0.113.2" # srgw1
  area2:
    gnbs:
      - "http://192.0.2.5:8080" # gnb3
    paths:
      nextmn-lite:
        - "203.0.113.3" # srgw2

logger:
  level: "trace"
